package pricing

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// liteLLMURL is LiteLLM's model_prices_and_context_window.json — the same
// source ccusage and our baked-in defaults reference, and the same URL the
// macapp's "Refresh pricing" uses. JSON-based and stable, unlike the docs
// page this fetcher originally scraped (whose selectors never matched the
// real page, so --refresh-pricing silently fell back to defaults).
const liteLLMURL = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"

// Fetch retrieves Anthropic pricing from LiteLLM and parses it into a Table.
func Fetch(ctx context.Context) (Table, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, liteLLMURL, nil)
	if err != nil {
		return Table{}, err
	}
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return Table{}, fmt.Errorf("fetch pricing: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return Table{}, fmt.Errorf("fetch pricing: status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return Table{}, err
	}
	return parseLiteLLM(body)
}

// liteLLMEntry mirrors the fields we read per model. LiteLLM stores costs
// per single token; we convert to per-1M.
type liteLLMEntry struct {
	Provider    string  `json:"litellm_provider"`
	InputCost   float64 `json:"input_cost_per_token"`
	OutputCost  float64 `json:"output_cost_per_token"`
	CacheCreate float64 `json:"cache_creation_input_token_cost"`
	CacheRead   float64 `json:"cache_read_input_token_cost"`
}

// parseLiteLLM extracts Anthropic and OpenAI models from LiteLLM's JSON.
// Mirrors the macapp's PricingFetcher.parse: filter to litellm_provider ==
// "anthropic" or "openai", strip any "anthropic/" name prefix, drop entries
// with no price.
func parseLiteLLM(body []byte) (Table, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		return Table{}, fmt.Errorf("parse pricing: %w", err)
	}
	const m = 1_000_000.0
	out := Table{Models: map[string]ModelPrice{}}
	for rawName, val := range raw {
		var e liteLLMEntry
		if err := json.Unmarshal(val, &e); err != nil {
			continue // non-object entries (e.g. spec strings)
		}
		// Anthropic and OpenAI both. Verified against the live LiteLLM
		// table: 26 anthropic and 145 openai entries survive the
		// non-zero-cost filter below, with no name collisions between
		// the two sets and no "/"-containing OpenAI names — so the
		// prefix-strip below needs no OpenAI equivalent.
		//
		// Caveat worth knowing: 52 of those OpenAI entries omit
		// cache_read_input_token_cost, which unmarshals to 0 and would
		// price cached reads free. Neither model Codex currently uses
		// (gpt-5.6-sol, gpt-5.6-luna) is among them, but cached reads
		// dominate Codex volume, so a future model landing in that set
		// would under-report rather than fail loudly.
		if !strings.EqualFold(e.Provider, "anthropic") && !strings.EqualFold(e.Provider, "openai") {
			continue
		}
		if e.InputCost <= 0 && e.OutputCost <= 0 {
			continue // placeholder entries
		}
		name := strings.TrimPrefix(rawName, "anthropic/")
		out.Models[name] = ModelPrice{
			InputPerMTok:         e.InputCost * m,
			OutputPerMTok:        e.OutputCost * m,
			CacheCreationPerMTok: e.CacheCreate * m,
			CacheReadPerMTok:     e.CacheRead * m,
		}
	}
	if len(out.Models) == 0 {
		return Table{}, fmt.Errorf("no priced models found in pricing JSON")
	}
	return out, nil
}

// SaveTOML writes a Table to disk as pricing.toml.
func SaveTOML(t Table, path string) error {
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by claudecounter. Fetched: " +
		time.Now().UTC().Format(time.RFC3339) + "\n")
	// schema must appear before any [models."..."] header: TOML resolves a
	// bare "key = value" line to whatever table is currently open, so if
	// this followed a [models...] block a decoder would read it as
	// models.<lastname>.schema instead of Table.Schema — Load would see
	// Schema == 0 forever and loadPricing would refetch on every run.
	fmt.Fprintf(&buf, "schema = %d\n\n", TableSchema)
	for name, p := range t.Models {
		fmt.Fprintf(&buf, "[models.%q]\n", name)
		fmt.Fprintf(&buf, "input_per_mtok = %g\n", p.InputPerMTok)
		fmt.Fprintf(&buf, "output_per_mtok = %g\n", p.OutputPerMTok)
		fmt.Fprintf(&buf, "cache_creation_per_mtok = %g\n", p.CacheCreationPerMTok)
		fmt.Fprintf(&buf, "cache_read_per_mtok = %g\n\n", p.CacheReadPerMTok)
	}
	return writeFileAtomic(path, buf.Bytes())
}

func writeFileAtomic(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
