package pricing

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
)

const pricingURL = "https://docs.anthropic.com/en/docs/about-claude/pricing"

// Fetch retrieves pricing from the Anthropic docs and parses it into a Table.
func Fetch(ctx context.Context) (Table, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, pricingURL, nil)
	if err != nil {
		return Table{}, err
	}
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return Table{}, fmt.Errorf("fetch pricing: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return Table{}, fmt.Errorf("fetch pricing: status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return Table{}, err
	}
	return parsePricingHTML(body)
}

// parsePricingHTML extracts a pricing Table from an HTML document.
// Selectors are pinned to the synthetic fixture schema; adjust once
// the real page is captured.
func parsePricingHTML(body []byte) (Table, error) {
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(body))
	if err != nil {
		return Table{}, err
	}
	out := Table{Models: map[string]ModelPrice{}}
	doc.Find("tr[data-model]").Each(func(_ int, s *goquery.Selection) {
		model, _ := s.Attr("data-model")
		if model == "" {
			return
		}
		parse := func(sel string) float64 {
			txt := strings.TrimSpace(s.Find(sel).First().Text())
			txt = strings.TrimPrefix(txt, "$")
			txt = strings.ReplaceAll(txt, ",", "")
			f, _ := strconv.ParseFloat(txt, 64)
			return f
		}
		out.Models[model] = ModelPrice{
			InputPerMTok:         parse("td.input"),
			OutputPerMTok:        parse("td.output"),
			CacheCreationPerMTok: parse("td.cache-write"),
			CacheReadPerMTok:     parse("td.cache-read"),
		}
	})
	if len(out.Models) == 0 {
		return Table{}, fmt.Errorf("no models found in pricing HTML")
	}
	return out, nil
}

// SaveTOML writes a Table to disk as pricing.toml.
func SaveTOML(t Table, path string) error {
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by claudecounter. Fetched: " +
		time.Now().UTC().Format(time.RFC3339) + "\n\n")
	for name, p := range t.Models {
		fmt.Fprintf(&buf, "[models.%q]\n", name)
		fmt.Fprintf(&buf, "input_per_mtok = %g\n", p.InputPerMTok)
		fmt.Fprintf(&buf, "output_per_mtok = %g\n", p.OutputPerMTok)
		fmt.Fprintf(&buf, "cache_creation_per_mtok = %g\n", p.CacheCreationPerMTok)
		fmt.Fprintf(&buf, "cache_read_per_mtok = %g\n\n", p.CacheReadPerMTok)
	}
	return writeFileAtomic(path, buf.Bytes())
}

func writeFileAtomic(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
